from fellowship_sim.base_classes import base_config

# Talent point configuration
TOTAL_TALENT_POINTS = 13

# Ultimatum affix
ULTIMATUM_AFFIX_CDR = 0.10

# Crit Bonus 20% affix (storm shield)
CRIT_BONUS_20_PERCENT_VALUE = 0.20

# Haste Bonus 20% affix (Shadow Lord / Empowered)
HASTE_BONUS_20_PERCENT_VALUE = 0.20

# Meteor Rain affix
METEOR_RAIN_INTERVAL_MIN = 100.0
METEOR_RAIN_INTERVAL_MAX = 120.0
METEOR_RAIN_SPIRIT_PER_METEOR = 2.0
METEOR_RAIN_NUMBER_OF_METEORS = 4

# Dark Prophecy
DARK_PROPHECY_PPM = 0.8
DARK_PROPHECY_BUFF_DURATION = 20.0
DARK_PROPHECY_HASTE_BONUS = 0.25

# Draconic Might
DRACONIC_MIGHT_PPM = 0.9
DRACONIC_MIGHT_BUFF_DURATION = 14.0
DRACONIC_MIGHT_MAIN_STAT_BONUS = 0.18

# Death's Grasp
DEATHS_GRASP_SPIRIT_BONUS = 0.03
DEATHS_GRASP_DAMAGE_BONUS = 0.15

# Drakheim's Absolution
DRAKHEIMS_ABSOLUTION_BUFF_DURATION = 20.0
DRAKHEIMS_ABSOLUTION_MAX_STACKS = 5
DRAKHEIMS_ABSOLUTION_MAIN_STAT_MULTIPLIER = 1.20

# Eldrin Deceit
ELDRIN_DECEIT_CRIT_BONUS = 0.03

# Haunting Lament
HAUNTING_LAMENT_SPIRIT_BONUS = 0.03

# Sin Warding
SIN_WARDING_EXPERTISE_BONUS = 0.03

# Sinthara's Veil
SINTHARAS_VEIL_SPIRIT_BONUS = 0.03

# Torment of Bael'Aurum
TORMENT_OF_BAELAURUM_MAIN_STAT_MULTIPLIER = 1.04

# Tuzari Grace
TUZARI_GRACE_HASTE_BONUS = 0.03

# Spirit of Heroism buff
SPIRIT_OF_HEROISM_DEFAULT_DURATION = 20.0
SPIRIT_OF_HEROISM_BASE_HASTE_BONUS = 0.30
SPIRIT_OF_HEROISM_VIRTUOSO_L1_HASTE_PENALTY = 0.03
SPIRIT_OF_HEROISM_VIRTUOSO_L2_HASTE_PENALTY = 0.09
SPIRIT_OF_HEROISM_SURGE_L1_MAIN_STAT_BONUS = 0.08
SPIRIT_OF_HEROISM_SURGE_L2_MAIN_STAT_BONUS = 0.24

# Base crit percent (default player aura)
BASE_CRIT_PERCENT = 0.05

# Randomize Player Percent HP
RANDOMIZE_PLAYER_HP_DEFAULT_HIGH_UPTIME = 0.80
RANDOMIZE_PLAYER_HP_DEFAULT_LOW_PERCENT = 0.70

# Gem power thresholds
GEM_UNLOCK_THRESHOLDS: list[int] = [120, 240, 480, 720, 960]
GEM_LEVELUP_THRESHOLDS: list[int] = [1200, 1560, 1920, 2280, 2640]
GEM_OVERCAP_THRESHOLD = 2640
GEM_TOTAL_MAX_POWER = 5256

# Gem Overcap bonus
GEM_OVERCAP_MAIN_STAT_BONUS_PER_POINT = 0.01 / 200

# Might of the Minotaur gem
MIGHT_OF_THE_MINOTAUR_HP_THRESHOLD = 0.80
MIGHT_OF_THE_MINOTAUR_STAT_BONUS_L1 = 0.03
MIGHT_OF_THE_MINOTAUR_STAT_BONUS_L2 = 0.09

# Champions Heart gem
CHAMPIONS_HEART_STAT_BONUS_L1 = 15
CHAMPIONS_HEART_STAT_BONUS_L2 = 45

# Blessing of the Conqueror gem
BLESSING_OF_THE_CONQUEROR_DAMAGE_MULTIPLIER_L1 = 1.05
BLESSING_OF_THE_CONQUEROR_DAMAGE_MULTIPLIER_L2 = 1.15

# Sealed Fate gem
SEALED_FATE_HP_THRESHOLD = base_config.HIGH_HEALTH_THRESHOLD
SEALED_FATE_CRIT_BONUS_L1 = 0.05
SEALED_FATE_CRIT_BONUS_L2 = 0.15

# Berserkers Zeal gem
BERSERKERS_ZEAL_CRIT_SCORE_L1 = 100
BERSERKERS_ZEAL_CRIT_SCORE_L2 = 300

# Killer Instinct gem
KILLER_INSTINCT_CRIT_BONUS_L1 = 0.03
KILLER_INSTINCT_CRIT_BONUS_L2 = 0.09

# Blessing of the Deathdealer gem
BLESSING_OF_THE_DEATHDEALER_CRIT_MULTIPLIER_L1 = 1.03
BLESSING_OF_THE_DEATHDEALER_CRIT_MULTIPLIER_L2 = 1.09

# Adrenaline Rush gem
ADRENALINE_RUSH_BUFF_DURATION = 10.0
ADRENALINE_RUSH_HASTE_BONUS_L1 = 0.03
ADRENALINE_RUSH_HASTE_BONUS_L2 = 0.09

# Thief's Alacrity gem
THIEFS_ALACRITY_HASTE_SCORE_L1 = 100
THIEFS_ALACRITY_HASTE_SCORE_L2 = 300

# First Strike gem
FIRST_STRIKE_BUFF_DURATION = 15.0
FIRST_STRIKE_EXPERTISE_BONUS_L1 = 0.05
FIRST_STRIKE_EXPERTISE_BONUS_L2 = 0.15

# Feline Grace gem
FELINE_GRACE_HASTE_BONUS_L1 = 0.03
FELINE_GRACE_HASTE_BONUS_L2 = 0.09

# Blessing of the Virtuoso gem
BLESSING_OF_THE_VIRTUOSO_HASTE_BONUS_L1 = 0.03
BLESSING_OF_THE_VIRTUOSO_HASTE_BONUS_L2 = 0.09

# Vanguard's Resolve gem
VANGUARDS_RESOLVE_EXPERTISE_SCORE_L1 = 100
VANGUARDS_RESOLVE_EXPERTISE_SCORE_L2 = 300

# Tactician's Acumen gem
TACTICIANS_ACUMEN_EXPERTISE_BONUS_L1 = 0.03
TACTICIANS_ACUMEN_EXPERTISE_BONUS_L2 = 0.09

# Blessing of the Commander gem
BLESSING_OF_THE_COMMANDER_CDR_L1 = 0.04
BLESSING_OF_THE_COMMANDER_CDR_L2 = 0.12

# Mystic's Intuition gem
MYSTICS_INTUITION_SPIRIT_SCORE_L1 = 100
MYSTICS_INTUITION_SPIRIT_SCORE_L2 = 300

# Oracle's Foresight gem
ORACLES_FORESIGHT_SPIRIT_BONUS_L1 = 0.03
ORACLES_FORESIGHT_SPIRIT_BONUS_L2 = 0.09

# Harmonious Soul gem
HARMONIOUS_SOUL_BUFF_DURATION = 5.0
HARMONIOUS_SOUL_MAX_STACKS = 10
HARMONIOUS_SOUL_STAT_BONUS_PER_STACK_L1 = 0.003
HARMONIOUS_SOUL_STAT_BONUS_PER_STACK_L2 = 0.009

# Stoic's Teachings gem
STOICS_TEACHINGS_MAIN_STAT_L1 = 25
STOICS_TEACHINGS_MAIN_STAT_L2 = 75

# Ancient's Wisdom gem
ANCIENTS_WISDOM_MAIN_STAT_MULTIPLIER_L1 = 1.03
ANCIENTS_WISDOM_MAIN_STAT_MULTIPLIER_L2 = 1.09

# Ancestral Surge gem
ANCESTRAL_SURGE_MAX_SPIRIT_BONUS_L1 = 10
ANCESTRAL_SURGE_MAX_SPIRIT_BONUS_L2 = 30

# Blessing of the Prophet gem
BLESSING_OF_THE_PROPHET_SOH_DURATION_BONUS_L1 = 6.0
BLESSING_OF_THE_PROPHET_SOH_DURATION_BONUS_L2 = 18.0
BLESSING_OF_THE_PROPHET_SPIRIT_COST_REDUCTION_L1 = 5.0
BLESSING_OF_THE_PROPHET_SPIRIT_COST_REDUCTION_L2 = 15.0

# Voidbringer's Touch weapon ability
VOIDBRINGERS_TOUCH_COOLDOWN = 90.0
VOIDBRINGERS_TOUCH_DEBUFF_DURATION = 15.0
VOIDBRINGERS_TOUCH_DAMAGE_ACCUMULATION_RATIO = 0.10
VOIDBRINGERS_TOUCH_MAX_STORED_DAMAGE_RATIO = 42.5
VOIDBRINGERS_TOUCH_BONUS_CRIT_PERCENT = 1.0

# Chronoshift weapon ability
CHRONOSHIFT_COOLDOWN = 180.0
CHRONOSHIFT_CHANNEL_DURATION = 3.0
CHRONOSHIFT_TICK_TIME = 1.5
CHRONOSHIFT_DAMAGE_MIN = 5192
CHRONOSHIFT_DAMAGE_MAX = 6345
CHRONOSHIFT_MAX_SECONDARY_TARGETS = 12
CHRONOSHIFT_CHANNEL_CDR_BONUS = 8.0

# Nature's Fury weapon ability
NATURES_FURY_COOLDOWN = 60.0
NATURES_FURY_DAMAGE_MIN = 12_579
NATURES_FURY_DAMAGE_MAX = 15_374
NATURES_FURY_SECONDARY_TARGETS = 3
NATURES_FURY_MAIN_DAMAGE_MULTIPLIER = 2.0
NATURES_FURY_CRIT_BONUS = 0.30

# Icicles of An'zhyr weapon ability
ICICLES_COOLDOWN = 40.0
ICICLES_DAMAGE_MIN = 1296
ICICLES_DAMAGE_MAX = 1584
ICICLES_DOT_DAMAGE_MIN = 345
ICICLES_DOT_DAMAGE_MAX = 422
ICICLES_MAX_SECONDARY_TARGETS = 12
ICICLES_CURSE_DAMAGE_MULTIPLIER = 3.0
ICICLES_CURSE_TICK_DURATION = 3.0

# Amethyst Splinters weapon trait
AMETHYST_SPLINTERS_DOT_DURATION = 8.0
AMETHYST_SPLINTERS_DOT_BASE_TICK_TIME = 2.0
AMETHYST_SPLINTERS_DAMAGE_RATIO_TABLE: list[float] = [0.07, 0.08, 0.09, 0.10]

# Diamond Strike weapon trait
DIAMOND_STRIKE_ECHO_DURATION = 20.0
DIAMOND_STRIKE_ECHO_MAX_STACKS = 5
DIAMOND_STRIKE_PPM_TABLE: list[float] = [5.0, 5.5, 6.1, 6.7]
DIAMOND_STRIKE_BASE_DAMAGE_TABLE: list[float] = [1480.0, 1780.0, 2000.0, 2370.0]
DIAMOND_STRIKE_BONUS_DAMAGE_PER_HARMONIOUS_SOUL_STACK = 0.35
DIAMOND_STRIKE_BONUS_DAMAGE_PER_ECHO_STACK = 0.40

# Emerald Judgement weapon trait
EMERALD_JUDGEMENT_PPM = 2.0
EMERALD_JUDGEMENT_BASE_DAMAGE_TABLE: list[float] = [6000.0, 7000.0, 8000.0, 9000.0]

# Sapphire Aurastone weapon trait
SAPPHIRE_AURASTONE_PULSE_INTERVAL = 3.0
SAPPHIRE_AURASTONE_RATIO_TABLE: list[float] = [0.07, 0.08, 0.09, 0.10]

# Visions of Grandeur weapon trait
VISIONS_OF_GRANDEUR_SP_RATE_TABLE: list[float] = [2.0, 2.4, 2.8, 3.2]
VISIONS_OF_GRANDEUR_SP_CDR_NORMALIZATION = 30.0

# Brave Machinations weapon trait
BRAVE_MACHINATIONS_CRIT_BONUS_TABLE: list[float] = [0.20, 0.24, 0.28, 0.32]
BRAVE_MACHINATIONS_CDR_ON_CRIT = 0.30

# Heroic Brand weapon trait
HEROIC_BRAND_DAMAGE_BONUS_TABLE: list[float] = [0.50, 0.60, 0.70, 0.80]

# Ruby Storm weapon trait
RUBY_STORM_PPM = 1.3
RUBY_STORM_DAMAGE_RATIO_TABLE: list[float] = [0.065, 0.078, 0.091, 0.104]
RUBY_STORM_MAX_SECONDARY_TARGETS = 7

# Martial Initiative weapon trait
MARTIAL_INITIATIVE_MAIN_STAT_BONUS = 0.10
MARTIAL_INITIATIVE_DURATION_RATIO_TABLE: list[float] = [0.20, 0.24, 0.28, 0.32]

# Hidden Power weapon trait
HIDDEN_POWER_PPM = 2.6
HIDDEN_POWER_STACK_DURATION = 60.0
HIDDEN_POWER_MAX_STACKS = 5
HIDDEN_POWER_REVEALED_BUFF_DURATION = 15.0
HIDDEN_POWER_MAIN_STAT_TABLE: list[float] = [0.075, 0.09, 0.105, 0.12]

# Hunter's Focus weapon trait
HUNTERS_FOCUS_BUFF_DURATION = 8.0
HUNTERS_FOCUS_MAX_STACKS = 5
HUNTERS_FOCUS_HASTE_PER_STACK_TABLE: list[int] = [20, 32, 43, 55]

# Inspired Allegiance weapon trait
INSPIRED_ALLEGIANCE_PPM = 1.2
INSPIRED_ALLEGIANCE_BUFF_DURATION = 8.0
INSPIRED_ALLEGIANCE_HASTE_SCORE_TABLE: list[int] = [85, 85, 85, 127]
INSPIRED_ALLEGIANCE_CDR_TABLE: list[float] = [2.0, 3.0, 4.0, 5.0]

# Kindling weapon trait
KINDLING_PPM = 2.1
KINDLING_DOT_DURATION = 9.0
KINDLING_DOT_TICK_DURATION = 3.0
KINDLING_DAMAGE_RATIO_TABLE: list[float] = [6.44, 7.70, 9.31, 11.20]
KINDLING_DAMAGE_RATIO_SCALE = 1000

# Navigator's Intuition weapon trait
NAVIGATORS_INTUITION_PROC_CHANCE = 0.20
NAVIGATORS_INTUITION_ICD = 90.0
NAVIGATORS_INTUITION_BUFF_DURATION = 30.0
NAVIGATORS_INTUITION_RATING_TABLE: list[int] = [276, 414, 552, 690]

# Patient Soul weapon trait
PATIENT_SOUL_EXPERTISE_SCORE_TABLE: list[int] = [107, 141, 177, 212]

# Seized Opportunity weapon trait
SEIZED_OPPORTUNITY_CRITS_REQUIRED = 20
SEIZED_OPPORTUNITY_BUFF_DURATION = 12.0
SEIZED_OPPORTUNITY_CRIT_SCORE_TABLE: list[int] = [112, 168, 224, 280]

# Vengeful Soul weapon trait
VENGEFUL_SOUL_PPM = 2.0
VENGEFUL_SOUL_BUFF_DURATION = 6.0
VENGEFUL_SOUL_MAIN_STAT_TABLE: list[float] = [0.04, 0.048, 0.056, 0.064]

# Willful Momentum weapon trait
WILLFUL_MOMENTUM_MAIN_STAT_BUFF_DURATION = 4.0
WILLFUL_MOMENTUM_MAIN_STAT_TABLE: list[float] = [0.03, 0.036, 0.042, 0.048]
WILLFUL_MOMENTUM_SPIRIT_RATING_TABLE: list[int] = [59, 89, 118, 148]
